# docker pull squidfunk/mkdocs-material
# docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
# docker run --rm -it -v ~/.ssh/tschaume@mac14:/root/.ssh/id_rsa -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy

site_name: 'MPContribs'
site_description: 'Contributed MP Materials Data'
site_author: 'Patrick Huck'
site_url: 'https://docs.mpcontribs.org'

repo_name: 'materialsproject/MPContribs'
repo_url: 'https://github.com/materialsproject/MPContribs'

copyright: 'Copyright &copy; 2019 Materials Project'

theme:
    name: 'material'
    feature:
        tabs: true

markdown_extensions:
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: materialsproject
        repo: MPContribs
    - pymdownx.mark
    - pymdownx.smartsymbols
    - footnotes

nav:
    - Get Started:
        - Introduction: index.md
        - Explore Data: portal.md
        - Contribute/Retrieve Data: api.md
    - Datasets:
        - Overview: datasets.md
        - RedoxThermoCSP: redox_thermo_csp/index.md
google_analytics:
    - 'UA-140392573-1'
    - 'auto'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/materialsproject'
    - type: 'twitter'
      link: 'https://twitter.com/persson_group'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/tschaume'
